export * from "./prismaPost.event"
export * from "./prismaPostAnnotationsUpdatedEvent"
export * from "./prismaPostCreatedEvent"
export * from "./prismaPostDeletedEvent"
export * from "./prismaPostUpdatedEvent"
